# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: required
dist: trusty

language: python

python:
  - "3.6"
  - "3.7"

services:
  - docker

before_install:
  - docker pull busybox

install:
  - pip install coveralls
  - pip install -r requirements_dev.txt
  - python setup.py install


script:
  - pytest -v -s -rs

after_success:
  coveralls
