# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: required
dist: trusty

language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: True


services:
  - docker

before_install:
  - docker pull busybox

install:
  - pip install coveralls
  - pip install -r requirements_dev.txt
  - python setup.py install


script:
  - pytest -v -s -rs

after_success:
  coveralls
