# -*- snakemake -*-
import os

configfile: "../config.yaml"
configfile: "config.yaml"

APPLICATION = "fastqc"
param = {
    'ref' : os.path.join("{version}", config['input']['ref']),
    'end': config['end'],
    'regions': config['params']['regions'],
}

BAM = os.path.join("../{end}", config['input']['bam'])


rule fastqc:
    input: bam=BAM, conda="fastqc-{version}.yaml"
    output: **config['fastqc']['fastqc']['output']
    conda: "fastqc-{version}.yaml"
    shell:
        "mkdir -p {wildcards.version} && " + \
            "fastqc --noextract {input.bam} -o {wildcards.version}/{wildcards.end}"

include: "../fileutils.sm"
