# -*- snakemake -*-
import os
import copy
from pytest_ngsfixtures.helpers import make_targets

configfile: "../config.yaml"
configfile: "config.yaml"

APPLICATION = "bcftools"

param = {
    'end': config['end'],
}

inputfiles = {
    'bam': os.path.join("../{end}", config['input']['bam']),
    'ref': os.path.join("../../ref", config['input']['ref']),
    'conda': "bcftools-{version}.yaml",
}

rule bcftools_call:
    input: **inputfiles
    output: **config[APPLICATION]["bcftools_call"]["output"]
    conda: APPLICATION + "-{version}.yaml"
    shell: "samtools mpileup -ug -f {input.ref} {input.bam} | bcftools call -vmO z -o {output}"

rule bcftools_stats:
    input: rules.bcftools_call.output.vcfgz
    output: **config[APPLICATION]["bcftools_stats"]["output"]
    conda: APPLICATION + "-{version}.yaml"
    shell: "bcftools stats {input} > {output.stats}"

           
include: "../fileutils.sm"
