# -*- snakemake -*-
import os
import copy
from pytest_ngsfixtures.helpers import make_targets

configfile: "../config.yaml"
include: "../fileutils.sm"

APPLICATION = "bcftools"

param = {
    'bam' : os.path.join("{version}", "{end}", config['input']['bam']),
    'ref': os.path.join("{version}", "{end}", config['input']['ref']),
    'end': config['end'],
    'version': config[APPLICATION]['_conda_versions'],
}

BAM = os.path.join("../{end}", config['input']['bam'])

rule bcftools_call:
    input: bam = BAM, ref = param['ref'], conda="bcftools-{version}.yaml"
    output: config[APPLICATION]["bcftools_call"]["output"]
    conda: APPLICATION + "-{version}.yaml"
    shell: "samtools mpileup -ug -f {input.ref} {input.bam} | bcftools call -vmO z -o {output}"
           
rule all:
    input: make_targets(workflow.rules, config, APPLICATION, end=param['end'], version=param['version'])
