# -*- makefile -*-
#!/usr/bin/make -rRf
SHELL=/bin/sh
.DELETE_ON_ERROR:
BWA=bwa
SAMTOOLS=samtools
BCFTOOLS=bcftools

SAMPLES=CHS.HG00512 CHS.HG00513 PUR.HG00731 PUR.HG00733 YRI.NA19238 YRI.NA19239
BAMFILES=$(foreach s, $(SAMPLES), $(s).bam)


ref.fasta: ../ref.fasta
	   ln -s $<

ref.fasta.sa: ref.fasta
	$(BWA) index $<

%.mem.bam: ref.fasta %_1.fastq.gz %_2.fastq.gz ref.fasta.sa
	$(BWA) mem -R '@RG\tID:$*\tSM:$*' $(word 1, $^) $(word 2, $^) $(word 3, $^) 2> $*.mem.log | $(SAMTOOLS) view -Sb - > $@

%.sort.bam: %.bam
	$(SAMTOOLS) sort  $< -o $@

all.bam: $(BAMFILES:%.bam=%.mem.sort.bam)
	$(SAMTOOLS) merge -f $@ $^

%.bam.bai: %.bam
	$(SAMTOOLS) index $<

%.vcf: %.bam %.bam.bai ref.fasta
	$(SAMTOOLS) mpileup -ug -f ref.fasta $(word 1, $^) | $(BCFTOOLS) call -vmO v -o $@

all: all.vcf
