{% set name = "pytest-ngsfixtures" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  path: ../../pytest-ngsfixtures
build:
  number: 0
  skip: False
  script: $PYTHON setup.py install --single-version-externally-managed --record record.txt
requirements:
  build:
    - python {{ python }}
    - setuptools
    - pytest-runner
  run:
    - python
    - pytest
    - docker-py

test:
  requires:
    - pytest
    - pytest-runner
    - docker-py
    - snakemake ==4.5.0

  imports:
    - pytest_ngsfixtures

about:
  home: https://github.com/percyfal/pytest-ngsfixtures.git
  license: GNU General Public License v3
  summary: 'Next-generation sequencing pytest fixtures.'
