# -*- snakemake -*-
import os

configfile: "../config.yaml"
configfile: "config.yaml"

APPLICATION = "cutadapt"
param = {
    'end': config['end'],
    'regions': config['params']['regions'],
    'threeprime': "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC",
    'fiveprime': "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT",
}

READ1 = os.path.join("../../yuge/CHS.HG00512_1.fastq.gz")
READ2 = os.path.join("../../yuge/CHS.HG00512_2.fastq.gz")

rule cutadapt:
    params: threeprime = param['threeprime'],
            fiveprime = param['fiveprime'],
            cmd = APPLICATION
    input: read1=READ1, read2=READ2, conda= APPLICATION + "-{version}.yaml"
    output: config['cutadapt']['cutadapt']['output']
    conda: APPLICATION + "-{version}.yaml"
    shell:
        "if [[ '{wildcards.end}' == 'se' ]]; then\n"
        "    {params.cmd} {input.read1} -a {params.threeprime} -o /dev/null > {output}\n"
        "else\n"
        "    {params.cmd} {input.read1} {input.read2} -a {params.threeprime} -A {params.fiveprime} -o /dev/null -p /dev/null > {output}\n"
        "fi\n"

include: "../fileutils.sm"
