# -*- snakemake -*-
import os
from pytest_ngsfixtures.helpers import make_targets

configfile: "../config.yaml"
include: "../fileutils.sm"

APPLICATION = "qualimap"
param = {
    'end': config['end'],
    'version': config[APPLICATION]['_conda_versions'],
}

BAM = os.path.join("../{end}", config['input']['bam'])

rule qualimap_bamqc:
    input: bam=BAM, conda="qualimap-{version}.yaml"
    output: config["qualimap"]["qualimap_bamqc"]["output"]
    conda: "qualimap-{version}.yaml"
    shell: "qualimap bamqc -bam {input.bam} -outdir {version} > {output}"
           
rule all:
    input: make_targets(workflow.rules, config, APPLICATION, end=param['end'], version=param['version'])
