# -*- snakemake -*-
import os

configfile: "../config.yaml"
configfile: "config.yaml"

APPLICATION = "gatk"

param = {
    'end': config['end'],
}

# Add required inputfiles here, or specify separately for each rule.
# The conda parameter is required.
inputfiles = {
    'conda': "gatk-{version}.yaml",
    'bam': os.path.join("../{end}", config['input']['bam']),
    'bai': os.path.join("../{end}", config['input']['bai']),
    'ref': os.path.join("../../ref", config['input']['ref']),
    'refidx': os.path.join("../../ref", config['input']['ref']),
    'dict': os.path.join("../../ref", config['input']['dict']),
    'known': os.path.join("../../ref", config['input']['known']),
}

_gatk_versions = {
    'dd785ee6' : '3.7',
}

def _gatk_register_version():
    try:
        version = _gatk_versions[wildcards.condatag]
        return "GenomeAnalysisTK-{}.tar.bz2".format(version)
    except:
        print("no such condatag; redefine _gatk_versions!")
        return []


rule gatk_register_version:
    input: _gatk_register_version
    output: ".snakemake/conda/{condatag}/bin/GenomeAnalysisTK"
    shell:
        "if [ -e {input.gatk} ]; then gatk-register {input.gatk}; fi;"


rule gatk_register:
    input: gatk37=".snakemake/conda/dd785ee6/bin/GenomeAnalysisTK"


rule gatk_haplotype_caller:
    input: rules.gatk_register.output, **inputfiles
    output: **config[APPLICATION]["gatk_haplotype_caller"]["output"]
    conda: APPLICATION + "-{version}.yaml"
    shell:
        "gatk -T HaplotypeCaller -I {input.bam} -R {input.ref} -o {output.vcfgz}"


rule gatk_varianteval:
    input: rules.gatk_register.output, vcf=rules.gatk_haplotype_caller.output.vcfgz, **inputfiles
    output: **config[APPLICATION]["gatk_varianteval"]["output"]
    conda: APPLICATION + "-{version}.yaml"
    shell:
        "gatk -T VariantEval -R {input.ref} --dbsnp {input.known} --eval {input.vcf} -o {output.stats}"


# Include rules for making the output
include: "../fileutils.sm"
